### ISSUE TITLE
writing

### ISSUE THREAD

**Issue by hyfj44255** [second-state/chat-with-chatgpt#364]
你是一位写作专家，我要写一个关于看不见更大的系统，陷入内卷的文章，但是缺一个素材来说明，你能帮我举个历史人物的例子吗，某某历史人物，看见了更大的系统，更值得做的事，跳出了内卷陷阱

**Comment by alabulei1** [comment]
Hello, I am your assistant on GitHub, built by the Second State team. I am ready for your question now!

If you are looking for a historical figure who recognized a larger system and prioritized more worthwhile endeavors, one example could be Mahatma Gandhi. He was a prominent leader during the Indian independence movement against British rule. Gandhi realized that the struggle for independence was not just about political change but also a larger social and cultural transformation. Rather than getting caught in the internal power struggles, he focused on nonviolent civil disobedience, promoting harmony between different religious and ethnic groups, and empowering the marginalized sections of society. By recognizing the larger goals and actions that were needed, Gandhi was able to break free from the confines of narrow thinking and contribute to a much grander cause.

**Comment by hyfj44255** [comment]
谢谢，能再给我一个素材吗

**Comment by alabulei1** [comment]
当然可以！如果你需要另一个历史人物的例子，你可以考虑阿尔贝·爱因斯坦。爱因斯坦是一位杰出的物理学家，他对相对论和量子力学的研究成果对科学界有着巨大的影响。然而，他也是一个思想家和社会活动家，非常关注社会正义和和平。在20世纪的上半叶，他目睹了两次世界大战的摧毁力量，因此，他从科学研究中更大的系统中解读到，人类社会需要更多的和平与合作。他发起和积极参与各种运动、联合国教科文组织和核武器禁止运动，致力于推动世界和平与摒弃战争。爱因斯坦的行动展示了他在看见更大系统的过程中，选择了更有价值的事情，跳出了内卷陷阱。
